### PR TITLE
Multiple updates

### PR DESCRIPTION
**Pull request by sssemil**
-Create configuration file in app. Checks if requested configuration file exists and returns stream or creates config and then returns stream.
-Better About menu
-Use --cleanconf
-Add superuser permissions
-Use android-23 API

### CODE REVIEW

**Comment by lgierth** [comment]
This is great -- thanks a lot. Let me have a look once I get home later tonight. One quick thing: we only stored the config file with the .apk because we had no way of generating it from within the app. Now that we have that, we can completely drop the pre-generated config file.

**Comment by sssemil** [comment]
By the way, there are some problems with parsing configuration. After removing all coments and comma in the end it's parsing without exceptions.

**Comment by lgierth** [comment]
Yep that's cjdns' dialect of JSON, you can make it valid JSON by piping it into `cjdroute --cleanconf`

**Comment by kpcyrd** [comment]
Looks good. Any further remarks? Otherwise I'd merge this.

**Comment by sssemil** [comment]
Nope, merge it, please.

**Pull request merged**
